name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches:
      - master
      - stable
  schedule:
    - cron: '0 8 * * 1' # Jeden Montag um 08:00 UTC

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (stable branch for schedule)
        if: github.event_name == 'schedule'
        uses: actions/checkout@v4
        with:
          ref: stable

      - name: Checkout repository (push event)
        if: github.event_name != 'schedule'
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v3
        with:
name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches:
      - master
      - stable
  schedule:
    - cron: '0 8 * * 1' # Jeden Montag um 08:00 UTC

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (stable branch for schedule)
        if: github.event_name == 'schedule'
        uses: actions/checkout@v4
        with:
          ref: stable

      - name: Checkout repository (push event)
        if: github.event_name != 'schedule'
        uses: actions/checkout@v4

      - name: Set image name in lowercase
        run: |
          IMAGE_NAME="${GITHUB_REPOSITORY,,}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tags for master branch
        if: github.ref == 'refs/heads/master' && github.event_name != 'schedule'
        run: |
          echo "TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nightly" >> $GITHUB_ENV

      - name: Set Docker tags for stable branch (push or schedule)
        if: github.ref == 'refs/heads/stable' || github.event_name == 'schedule'
        run: |
          echo "TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stable,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.TAGS }}
          provenance: false